DATA WORK.COUNTY;
SET MAPSGFK.US_COUNTIES_ATTR;

LENGTH GEOID $5.;

GEOID=SUBSTR(ID,4,5); /*THIS WILL MAP TO GEOID IN COUNTY SHAPE FILE */
RUN;



DATA WORK.ZIP;
SET SASHELP.ZIPCODE;

LENGTH GEOID10 $5.;

GEOID10=TRIM(PUT(ZIP,z5.));

rename 
x=my_x
y=my_y
STATE = TEMP_STATE
COUNTY = TEMP_COUNTY;

KEEP ZIP GEOID10 X Y STATE COUNTY;
RUN;


PROC SQL;
CREATE TABLE WORK.COUNTY_ZIP AS
SELECT A.*,B.ZIP,B.GEOID10,B.MY_X,B.MY_Y FROM WORK.COUNTY A INNER JOIN WORK.ZIP B ON A.STATE=B.TEMP_STATE AND A.COUNTY=B.TEMP_COUNTY;
QUIT;


DATA WORK.CLAIM_GEO_1;
SET WORK.COUNTY_ZIP;
/* WHERE STATECODE IN ('MO','AR','KS','OK'); */
LABEL IDNAME='County';
rename IDNAME=COUNTY_NAME;

KEEP STATECODE STATE GEOID GEOID10 IDNAME;
RUN;


/*********** DATA BELOW WILL BE JOINED TO CLAIM DATA SO THAT WE CAN MAP OUR DATA */
/* CREATING RIGHT AMOUNT OF GEO RECORDS SO THAT WHEN ME MERGE TO PREM_LOSS DATA IT GOES SMOOTHLY */
%MACRO SCALE_ZIP;
	DATA WORK.SCALE_ZIP;
		SET %DO I=1 %TO 2;
			WORK.CLAIM_GEO_1 %END;
		;
	RUN;
		
	DATA WORK.SCALE_ZIP2;
		SET WORK.SCALE_ZIP (OBS=46489);
		JOIN_TO_POL=_n_;
		LABEL STATECODE='State'
	  	STATE='State Number';
	RUN;

%MEND SCALE_ZIP;

%SCALE_ZIP